name = "spawnlab-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "JOBS"
id = "6ea018fb02dd4d5eba701758194ea6b3"
preview_id = "c74f0b4dc9c044c09b311a0e46459533"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "spawnlab-assets"

[triggers]
crons = ["* * * * *"]

[vars]
WORKER_URL = "https://spawnlab-worker.anivanis.workers.dev"

# Secrets (set via: wrangler secret put <NAME>)
# WORKER_SECRET  — shared secret between CF Worker and GPU workers
